# Generated by Django 3.0.4 on 2021-08-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notesid', models.IntegerField()),
                ('notestitle', models.CharField(max_length=50)),
                ('notesdesc', models.CharField(max_length=50)),
                ('notespages', models.IntegerField()),
            ],
        ),
    ]
