# Generated by Django 3.0.4 on 2021-08-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prodname',
            field=models.CharField(max_length=50),
        ),
    ]
